### ISSUE TITLE
Issue with device running Oero.

### ISSUE THREAD

**Issue by prashantwosti** [divyanshub024/ChatBot#1]
Tried compiling and running this code in Oreo but got NoClassDefFoundError. Runs without any issue on devices below oero.

`09-23 11:02:28.842 3041-3041/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.beast.chatbot, PID: 3041
                                                 java.lang.NoClassDefFoundError: org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup
                                                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                     at org.apache.logging.log4j.core.util.ReflectionUtil.instantiate(ReflectionUtil.java:185)
                                                     at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:65)
                                                     at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:346)
                                                     at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:161)
                                                     at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:359)
                                                     at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:420)
                                                     at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:138)
                                                     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
                                                     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
                                                     at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
                                                     at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:426)
                                                     at ai.api.AIDataService.<clinit>(AIDataService.java:59)
                                                     at ai.api.android.AIService.<init>(AIService.java:81)
                                                     at ai.api.services.GoogleRecognitionServiceImpl.<init>(GoogleRecognitionServiceImpl.java:89)
                                                     at ai.api.android.AIService.getService(AIService.java:68)
                                                     at com.example.beast.chatbot.MainActivity.onCreate(MainActivity.java:70)
                                                     at android.app.Activity.performCreate(Activity.java:6975)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
                                                     at org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup.<clinit>(JmxRuntimeInputArgumentsLookup.java:35)
                                                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                     at org.apache.logging.log4j.util.LoaderUtil.newInstanceOf(LoaderUtil.java:138)
                                                     at org.apache.logging.log4j.util.LoaderUtil.newCheckedInstanceOf(LoaderUtil.java:163)
                                                     at org.apache.logging.log4j.core.util.Loader.newCheckedInstanceOf(Loader.java:311)
                                                     at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:103)
                                                     at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:104)
                                                     at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:30)
                                                     at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:61)
                                                     at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
                                                     at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
                                                     at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
                                                     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:142)
                                                     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41) 
                                                     at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175) 
                                                     at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:426) 
                                                     at ai.api.AIDataService.<clinit>(AIDataService.java:59) 
                                                     at ai.api.android.AIService.<init>(AIService.java:81) 
                                                     at ai.api.services.GoogleRecognitionServiceImpl.<init>(GoogleRecognitionServiceImpl.java:89) 
                                                     at ai.api.android.AIService.getService(AIService.java:68) 
                                                     at com.example.beast.chatbot.MainActivity.onCreate(MainActivity.java:70) 
                                                     at android.app.Activity.performCreate(Activity.java:6975) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
09-23 11:02:28.842 3041-3041/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/com.example.beast.chatbot-stW_tU5Q_ZBhHjdS6Jx3dg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.beast.chatbot-stW_tU5Q_ZBhHjdS6Jx3dg==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
`

**Comment by prashantwosti** [comment]
SOLVED!

updated to version 1.6.11 and its solved. :)

`compile 'ai.api:libai:1.6.11'`

**Comment by Uday2024** [comment]
Can u share your gradle file I am also facing same problem I updated the api library but facing same problem.
